[package]
authors = ["Polygon <polygon@wh2.tu-dresden.de>"]
name = "stm32f407-fix"
version = "0.1.0"
[dependencies]
bare-metal = "0.2.0"
cortex-m = "0.5.1"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.5.0"

[features]
rt = ["cortex-m-rt/device"]
